name:               "Yike"
description:        "A minimalistic jekyll theme for humans"

url:                "yike-chen.github.io"
author:             "thinker3197"
email:              "hi_lang@foxmail.com"
gravatar_hash:      "72166dd7e43ead86278f20a62ad0c393"
#twitter:            "jhondoe"
email:              "hi_lang@foxmail.com"
github:             "yike-chen"
#pinterest:          "jhondoe"
#linkedin:           "jhondoe"
#facebook:           "jhondoe"

disqus_shortname:   "Yike"

background:         "back.jpg"

paginate:           10
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate